FROM mcr.microsoft.com/dotnet/sdk:8.0 AS build
WORKDIR /src
COPY UserLogin.csproj .
RUN dotnet restore UserLogin.csproj
COPY . .
RUN dotnet ef database update --project UserLogin.csproj --context AppDbContext
RUN dotnet build UserLogin.csproj

FROM build AS publish
RUN dotnet publish UserLogin.csproj -c Release -o /app/publish

FROM mcr.microsoft.com/dotnet/aspnet:8.0 AS final
WORKDIR /app
COPY --from=publish /app/publish .
ENTRYPOINT ["dotnet", "UserLogin.dll"] 
