FROM mcr.microsoft.com/dotnet/sdk:8.0 AS build
WORKDIR /src
COPY ../UserLogin/UserLogin.csproj .
RUN dotnet restore UserLogin.csproj
COPY ../UserLogin .
RUN dotnet build UserLogin.csproj

FROM build AS publish
RUN dotnet publish UserLogin.csproj -c Release -o /app/publish

FROM base AS final
WORKDIR /app
COPY --from=publish /app/publish .
ENTRYPOINT ["dotnet", "UserLogin.dll"] 
